version: '2'
services:
    jtasks-app:
        image: jtasks
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jtasks-mariadb:3306/jtasks
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jtasks-mariadb:
        extends:
            file: mariadb.yml
            service: jtasks-mariadb
